"""empty message

Revision ID: 974f79a95b09
Revises: b4da0d1b7a7b
Create Date: 2016-10-19 20:44:44.732384

"""

# revision identifiers, used by Alembic.
revision = '974f79a95b09'
down_revision = 'b4da0d1b7a7b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
