"""empty message

Revision ID: d39ace46d9b7
Revises: 49738ee20be3
Create Date: 2016-10-21 18:04:38.708835

"""

# revision identifiers, used by Alembic.
revision = 'd39ace46d9b7'
down_revision = '49738ee20be3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_comments_timestamp'), 'comments', ['timestamp'], unique=False)
    op.drop_index('ix_comments_tiemstamp', table_name='comments')
    op.drop_column('comments', 'tiemstamp')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('tiemstamp', sa.DATETIME(), nullable=True))
    op.create_index('ix_comments_tiemstamp', 'comments', ['tiemstamp'], unique=False)
    op.drop_index(op.f('ix_comments_timestamp'), table_name='comments')
    op.drop_column('comments', 'timestamp')
    ### end Alembic commands ###
